"""Add event_bands association table

Revision ID: add_event_bands_table
Revises: 5f77853bebb5
Create Date: 2025-01-08 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_event_bands_table'
down_revision = '5f77853bebb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建 event_bands 关联表
    op.create_table('event_bands',
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('band_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
        sa.PrimaryKeyConstraint('event_id', 'band_id')
    )
    
    # 添加索引以提高查询性能
    op.create_index(op.f('ix_event_bands_band_id'), 'event_bands', ['band_id'], unique=False)
    op.create_index(op.f('ix_event_bands_event_id'), 'event_bands', ['event_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除索引
    op.drop_index(op.f('ix_event_bands_event_id'), table_name='event_bands')
    op.drop_index(op.f('ix_event_bands_band_id'), table_name='event_bands')
    
    # 删除表
    op.drop_table('event_bands')
    
    # ### end Alembic commands ###
